# Generated by Django 3.2.9 on 2021-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPfinalcoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cakes',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dessert',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
