# Generated by Django 3.2.9 on 2021-12-17 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPfinalcoder', '0003_auto_20211208_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bakery'),
        ),
        migrations.AddField(
            model_name='cakes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cakes'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='desserts'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 6, 26, 8, 115660)),
        ),
        migrations.AlterField(
            model_name='cakes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 6, 26, 8, 112661)),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 6, 26, 8, 114661)),
        ),
    ]
