# Generated by Django 4.0 on 2021-12-28 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPfinalcoder', '0004_auto_20211217_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 14, 37, 22, 17467)),
        ),
        migrations.AlterField(
            model_name='cakes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 14, 37, 22, 17467)),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 14, 37, 22, 17467)),
        ),
    ]
