# Generated by Django 4.0 on 2021-12-28 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPfinalcoder', '0005_alter_bakery_date_alter_cakes_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPfinalcoder.cakes'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 16, 52, 53, 990991)),
        ),
        migrations.AlterField(
            model_name='cakes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 16, 52, 53, 990991)),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 16, 52, 53, 990991)),
        ),
    ]
